name: Test the package in the browser
on: push
jobs:
  test:
    name: Test the package functionality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run test script
        run: node test/puppeteer.js
